### ISSUE TITLE
Change Stylus Default Rotation

### ISSUE THREAD

**Issue by SybelBlue** [SybelBlue/trombone-input#10]
Figure out what the bounds should be for the rotation (maybe two modes of use for at side or in front)
Design way of putting initial rotation

**Comment by bretjackson** [comment]
z should probably range -60  to 60 with zero at the top. Didn't seem to work properly with min at -80 and max at 80

**Comment by bretjackson** [comment]
Make display like FPS.cs that displays both euler angles and normalized values

**Comment by bretjackson** [comment]
Need to determine inverse issue for z rotation (left-handed?)
