### ISSUE TITLE
Challenge transitions

### ISSUE THREAD

**Issue by bretjackson** [SybelBlue/trombone-input#17]
Make Lobby scene (simple room)
Between layouts transition to the lobby automatically. After a keypress (?) transition to the main scene with the next layout practice. 

Maybe use input file to command scene transitions

**Comment by bretjackson** [comment]
Here's an example project. See runexperiment.cs https://github.com/tinker-lab/bema-annotation

**Comment by zspilka** [comment]
What I have so far is the there is a start button which will additively onload the trial scene. Then when the user completes the trial, they scene is offloaded and they must hit the end trial button. Apon doing this, they jump back into the lobby scene, and, when they are ready, hit the start button again to continue with the trials and do the next one.

While not 100% automated, the program and scene switching does work fairly well. Now, I need to figure out how to use the key press trigger for the return button.

**Comment by zspilka** [comment]
Now the transition from trials to lobby is fully automated. Now I need to work on key press/key events

**Comment by zspilka** [comment]
With my most recent commit, the user or proctor can seamlessly transition between the lobby and trial scenes using the return key on the keyboard.
