### ISSUE TITLE
Detect up/down events on slider

### ISSUE THREAD

**Issue by bretjackson** [SybelBlue/trombone-input#20]
Detect up/down slider events and store or calculate the last value before release.

Potentially have a sliding window of values, discard values where the delta is above a threshold?

**Comment by bretjackson** [comment]
Bret: record values with timestamps using the stylus then assign to Logan

**Comment by SybelBlue** [comment]
Filter was created and incorporated, waiting on testing

**Comment by SybelBlue** [comment]
Used python simulation to try and fine tune automatic filter input generation
