### ISSUE TITLE
Raycast with stylus doesn't respond to button clicks

### ISSUE THREAD

**Issue by bretjackson** [SybelBlue/trombone-input#22]

**Comment by SybelBlue** [comment]
Is this still an issue? Was this in reference to the dropdown not acting as expected?

**Comment by bretjackson** [comment]
Yes, it's still an issue. I can get the drop down to highlight, but it won't respond to the button clicks (i.e. the layout is always constant and doesn't cycle through.)

I can tell the button presses are working because it does add letters to the output. I'm not sure if that's stealing the input from the dropdown, but we probably want to make sure if a button or other ui element is raycast highlighted then the layouts don't take the button press as a sign to input letters.

Normal buttons (start trials button in the lobby) will also not respond to a click. We probably need to map the vr button event to the pressed/clicked event for unity ui things.
