### ISSUE TITLE
Paper Writing and video

### ISSUE THREAD

**Issue by bretjackson** [SybelBlue/trombone-input#33]
Paper parts:
- Title
- Abstract
- Intro
- Related work (Logan)
- ... taxonomy?
- Description of 2-3 interfaces (circular, two axis, linear?) TODO: name these (Logan, Zahara)
- Evaluation
- Limitations
- Conclusions

- figures (Zahara)
  - teaser
  - diagrams showing how the interfaces work
  - more? 

Video:
- script? 
- recording
- editing

**Comment by SybelBlue** [comment]
# Name Brainstorm

## Linear Layout
- Linear
- Slider-Only
- TapType

> defining features
> - One-Dimensional layout
> - Requires stylus hardware layout

## Stylus Binned ABCDE
- Fin Type
- Radial Type
- Shell Layout
- Rainbow Layout
- Arch-Type
- Pizza-Strip Layout
- Wing Layout


> defining features
> - Tilt to select bin
> - Slide to select letter

## Two Rot Binned ABCDE
- Two-Axis Rotary
- Tilt-Type
- Casted Net Layout (keys mapped to their angles look like a net)

> defining features
> - Forearm supination to select bin
> - Wrist flexion to select letter
> - Most extensible to other hardwares

## Stylus-Point Raycast
> defining features
> - Mostly not ours

**Comment by SybelBlue** [comment]
Finished first draft of related work, introduction

**Comment by SybelBlue** [comment]
Assigned me:
Taxonomy
Conclusion

talk about trial & challenge structure

**Comment by bretjackson** [comment]
Some other possibilities for the naming the circular layout:

- Arc Type
- Radial-Slide Type

I'm sort of leaning towards Arc type. What do you think?

**Comment by SybelBlue** [comment]
Title Ideas:
- Arc-Type and Tilt-Type : Pen-based Immersive Input / for Room-Scale VR
- Pen-based Text Input : Two Novel Interfaces / for VR Stylus
- Novel, Immersive / Interfaces for Input / in Room-Scale VR
- Arc-Type and Tilt-Type : Virtual Reality / Pen-Based Text Input
- Effortless Typing / in Full VR Immersion: Arc-Type and Tilt-Type
